version: '3.8'

services:

  db:
    image: mysql:8.0.42
    container_name: locadora-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: locadora
    ports:
      - "7200:3306"
    volumes:
      - ./db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p1234"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: ./
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app